<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/vendor/composer/autoload_real.php';
//require_once '/composer/autoload_real.php';

return ComposerAutoloaderInit6b6619d2a200691320dbbd4b433131b1::getLoader();
